AWSTemplateFormatVersion: '2010-09-09'
Description: My S3 static website

Parameters:
  DomainName:
    Description: Domain name of website
    Type: String
    Default: useraddmario.com
  PipelineID:
    Description: Unique identifier.
    Type: String
  DomainNameOrg:
    Description: .org
    Type: String
    Default: useraddmario.org
  S3Logs:
    Description: S3 Logs bucket
    Type: String
    Default: aws-cloudtrail-logs-089634162715-b8e00a06

Resources:
  S3BucketRoot:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub '${DomainName}'
      LoggingConfiguration:
        DestinationBucketName: !Ref S3Logs
        LogFilePrefix: 'cdn/'

  S3BucketSub:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub 'www.${DomainName}'
      AccessControl: BucketOwnerFullControl
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref DomainName

  S3BucketOrgSub:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub 'www.${DomainNameOrg}'
      AccessControl: BucketOwnerFullControl
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref DomainName

  S3BucketSubOrg:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref DomainNameOrg
      AccessControl: BucketOwnerFullControl
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref DomainName

Outputs:
  PipelineID:
    Description: Pipeline ID to clean up after the next deployment
    Value: !Sub ${PipelineID}
    Export:
      Name: PipelineID
  S3BucketRoot:
    Description: Root bucket ARN
    Value: !GetAtt S3BucketRoot.Arn
    Export:
      Name: S3BucketRoot
