version: 2.1

parameters:
  domain:
    type: string
    default: "useraddmario.org"

commands:
  dependencies:
    steps:
      - run: yum -y install tar less gzip # needed to attach_workspace

jobs:
  update_cloudfront_dist:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: update cloudFront distribution
          command: |
            # pwd in /root/project by default
            cd .circleci
            # check if stack exists, if so update else deploy
            present=$(aws cloudformation list-stacks \
              --stack-status-filter "CREATE_COMPLETE" "UPDATE_COMPLETE" \
              --query 'StackSummaries[?StackName==`useraddmario.com`].StackName[]' \
              --output text)
            echo $present
            echo $CIRCLE_WORKFLOW_ID
            echo ${CIRCLE_WORKFLOW_ID:0:7}
            if [ "$present" == "useraddmario.com" ]
            then
              aws cloudformation update-stack \
                --stack-name useraddmario.com \
                --template-body file://final_infra.yml \
                --parameters ParameterKey=PipelineID,ParameterValue=${CIRCLE_WORKFLOW_ID:0:7}
                #--template-body file://cloudfront.yml
            else
              aws cloudformation deploy \
                --stack-name useraddmario.com \
                --template-file ./final_infra.yml \
                --parameter-overrides PipelineID=${CIRCLE_WORKFLOW_ID:0:7}
                #--template-file ./cloudfront.yml \
            fi
           
            aws s3 cp index.html s3://useraddmario.com/

workflows:
  deploy_workflow:
    jobs:
      - update_cloudfront_dist:
          context: aws
