Parameters:
  PipelineID2:
    Description: Unique identifier.
    Type: String
  DomainName:
    Description: Domain/S3 bucket name
    Type: String
    Default: useraddmario.com
  SubDomain:
    Description: Subdomain
    Type: String
    Default: www.useraddmario.com
  CertificateArn:
    Description: cert arn
    Type: String
    Default: arn:aws:acm:us-west-2:089634162715:certificate/0cd88b0b-d816-4077-a776-1339e3450906

Resources:
  PortfolioDist:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          ViewerProtocolPolicy: redirect-to-https
          DefaultTTL: 3600
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: true
          TargetOriginId: !Join
            - ''
            - - Sub! '${DomainName}.s3-website.'
              - !Ref "AWS::Region"
              - '.amazonaws.com'
        Enabled: 'true'
        Aliases:
        - !Ref SubDomain
        Origins:
        - DomainName: !Join
            - ''
            - - Sub! '${DomainName}.s3-website.'
              - !Ref "AWS::Region"
              - '.amazonaws.com'
          Id: !Ref DomainName
          OriginPath: !Sub "/portfolio-${PipelineID2}"
          #S3OriginConfig:
          #  OriginAccessIdentity: !Join 
          #    - ''
          #    - - 'origin-access-identity/cloudfront/'
          #      - !Ref CloudFrontOriginAccessIdentity
          CustomOriginConfig:
            OriginProtocolPolicy: match-viewer
        DefaultRootObject: index.html
        PriceClass: PriceClass_200
        ViewerCertificate:
          AcmCertificateArn: !Ref 'CertificateArn'
          MinimumProtocolVersion: TLSv1.2_2019
          SslSupportMethod: 'sni-only'

  Route53RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub '${DomainName}.'
      RecordSets:
      - Name: !Sub '${SubDomain}'
        Type: 'A'
        AliasTarget:
          DNSName: !GetAtt 'PortfolioDist.DomainName'
          EvaluateTargetHealth: false
          # Always this HostedZoneId for CF
          HostedZoneId: 'Z2FDTNDATAQYW2'

  ApexRoute53RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub '${DomainName}.'
      RecordSets:
      - Name: !Ref 'DomainName'
        Type: 'A'
        AliasTarget:
          DNSName: !GetAtt 'PortfolioDist.DomainName'
          EvaluateTargetHealth: false
          # Always this HostedZoneId for CF
          HostedZoneId: 'Z2FDTNDATAQYW2'
Outputs:
  PipelineID2:
    Description: Pipeline ID for current deployment
    Value: !Sub ${PipelineID2}
    Export:
      Name: PipelineID2
  PortfolioDistribution:
    Description: CloudFront Distribution ID
    Value: !Ref PortfolioDist
    Export:
      Name: PortfolioDistributionID
